# -*- coding: utf-8 -*-
# Contenido Oct-Dic 2026. Fuente de ideas: textos de Karina (eBook, Substack, mensaje del 9 oct 2026).
NL = "Más en mi newsletter: enlace en el perfil."
DISC = "Información general sobre Costa Rica. No sustituye asesoría jurídica."
H = {
 "pat": "#MujeresYDinero #Patrimonio #AutonomiaEconomica #EmprendedorasCR #FinanzasPersonales",
 "emp": "#EmprendedorasCR #Emprendimiento #MujeresYDinero #AutonomiaEconomica #Patrimonio",
 "ley": "#SociedadesMercantiles #CostaRica #DerechoParaEmprendedoras #EmprendedorasCR #Patrimonio",
 "esc": "#MujeresGenerandoseRiqueza #MujeresYDinero #AutonomiaEconomica #Escritoras #EmprendedorasCR",
}
PIECES = [
# ---------------- SEMANA 1
dict(id="W01", tema="Ingresos vs. patrimonio", fecha_c="2026-10-13", fecha_li="2026-10-14", fecha_s="2026-10-15", slug="ingresos-vs-patrimonio",
 flags=["Basado en tu título y en tu frase del Substack 'El libro'."], verificar=[],
 c_slides=[
  ("cover","No es lo mismo generar ingresos que consolidar un patrimonio","Una diferencia que casi nadie nos explicó"),
  ("statement","Generar ingresos es lo que entra cada mes. Consolidar un patrimonio es lo que queda, lo que está a tu nombre y lo que está protegido.",""),
  ("question","¿Qué de lo que hoy usás figura realmente a tu nombre?","Una cosa es usarlo. Otra es que sea tuyo en los registros.",None),
  ("question","¿Qué parte de lo que ganás se convierte en algo que dura?","Ahorro, bienes, derechos, un negocio ordenado.",None),
  ("question","¿Qué pasaría con lo que construiste si no pudieras trabajar por un tiempo?","Pensarlo también es parte de construirlo.",None),
  ("quote","Se puede trabajar toda una vida entera y aun así no lograr un patrimonio propio, si nadie nos explicó cómo hacerlo.",""),
  ("close","Esa explicación es lo que faltaba. Empecemos por ahí.",NL),
 ],
 c_ig="Ganar bien no es lo mismo que construir patrimonio.\n\nHay mujeres con educación, con experiencia y con negocios funcionando que saben generar ingresos y casi nada sobre cómo consolidarlos en algo propio. No es descuido: es que nadie nos lo explicó.\n\nTres preguntas para empezar. ¿Cuál te cuesta más contestar? Contámelo en los comentarios.\n\nMás en mi newsletter, enlace en el perfil.",
 c_fb="Ganar bien no es lo mismo que construir patrimonio.\n\nHay mujeres con educación, con experiencia y con negocios funcionando que saben generar ingresos, y casi nada sobre cómo consolidarlos en algo propio. No es descuido: es que durante generaciones las estructuras y las creencias limitaron nuestra relación con la riqueza y con el poder económico.\n\nEn las diapositivas dejé tres preguntas para empezar. ¿Cuál te cuesta más contestar?",
 c_h=H["pat"], c_alt="Carrusel de 7 diapositivas con fondo malva y fondos claros. Título: No es lo mismo generar ingresos que consolidar un patrimonio. Tres preguntas sobre bienes a tu nombre, ingresos que duran y qué pasa si no podés trabajar. Cierre: Esa explicación es lo que faltaba. Empecemos por ahí.",
 c_cta="Comentar cuál pregunta cuesta más; newsletter en el perfil",
 s=("quote","Se puede trabajar toda una vida y aun así no lograr un patrimonio propio, si nadie nos explicó cómo hacerlo.",""),
 s_ig="Tal vez a vos tampoco te lo explicaron. Compartila con una mujer que necesite leerlo.", s_fb="Tal vez a vos tampoco te lo explicaron. Compartila con una mujer que necesite leerlo y contame qué pensás.",
 s_h="#MujeresYDinero #Patrimonio #AutonomiaEconomica", s_alt="Imagen malva con la frase: Se puede trabajar toda una vida y aun así no lograr un patrimonio propio, si nadie nos explicó cómo hacerlo.", s_cta="Compartir",
 li="No es lo mismo generar ingresos que consolidar un patrimonio.\n\nDurante más de quince años acompañé negocios y patrimonios, y vi el mismo patrón en mujeres con educación, con experiencia y con negocios funcionando: sabían generar ingresos, pero tenían poca información sobre cómo gestionar su propio patrimonio.\n\nNo era descuido. Era el resultado de estructuras y creencias que, durante generaciones, limitaron nuestra relación con la riqueza y con el poder económico.\n\nTres preguntas que conviene hacerse:\n1. ¿Qué de lo que usás figura realmente a tu nombre?\n2. ¿Qué parte de lo que ganás se convierte en algo que dura?\n3. ¿Qué pasaría con lo que construiste si no pudieras trabajar por un tiempo?\n\nEscribo sobre esto en mi newsletter y en mi libro. ¿Cuál de las tres te cuesta más contestar?",
 li_h="#AutonomiaEconomica #Emprendimiento #Patrimonio"),
# ---------------- SEMANA 2
dict(id="W02", tema="Emprendimiento vs. patrimonio", fecha_c="2026-10-20", fecha_li="2026-10-21", fecha_s="2026-10-22", slug="emprendimiento-vs-patrimonio",
 flags=["Basado en tu título de artículo. El desarrollo es propuesta mía: corregilo."], verificar=[],
 c_slides=[
  ("cover","No es igual crear un emprendimiento que crear un patrimonio","Y confundirlos tiene un costo"),
  ("list","Un emprendimiento",["Vende y factura","Produce un flujo de dinero","Depende de tu trabajo y tu energía","Puede crecer, cambiar o cerrar"]),
  ("list","Un patrimonio",["Bienes y derechos que son tuyos","Está protegido y documentado","Dura más que un buen mes","Se revisa y se mantiene"]),
  ("statement","Un negocio puede producir mucho y aun así no dejarte nada propio.",""),
  ("question","¿Lo que ganás con tu negocio termina en bienes tuyos o en gastos del negocio y de la casa?","",None),
  ("question","¿Está separado lo que es del negocio de lo que es tuyo?","Esa separación protege a las dos partes.",None),
  ("close","Primero se entiende la diferencia. Después se decide qué construir.",NL),
 ],
 c_ig="Un emprendimiento y un patrimonio no son lo mismo.\n\nEl primero vende, factura y depende de tu trabajo. El segundo es lo que queda a tu nombre, protegido y documentado. Un negocio puede producir mucho y no dejarte nada propio.\n\nPregunta de hoy: ¿lo que ganás termina en bienes tuyos o en gastos del negocio y de la casa?",
 c_fb="Un emprendimiento y un patrimonio no son lo mismo.\n\nEl primero vende, factura y depende de tu trabajo y tu energía. El segundo es lo que queda a tu nombre, protegido y documentado. Un negocio puede producir mucho y aun así no dejarte nada propio.\n\nMe gustaría saber cómo lo vivís vos: ¿lo que ganás termina en bienes tuyos o se va en gastos del negocio y de la casa?",
 c_h=H["emp"], c_alt="Carrusel de 7 diapositivas. Compara un emprendimiento (vende, factura, depende de tu trabajo) con un patrimonio (bienes y derechos propios, protegidos y documentados) y plantea dos preguntas sobre separar negocio y finanzas personales.", c_cta="Responder la pregunta en comentarios",
 s=("question","¿Tu negocio te da ingresos o te está dejando bienes?",""),
 s_ig="Pensalo con calma. Las dos respuestas son información valiosa.", s_fb="Pensalo con calma: las dos respuestas son información valiosa. Si querés, contame en los comentarios cómo lo ves hoy.",
 s_h="#EmprendedorasCR #Patrimonio #MujeresYDinero", s_alt="Imagen clara con la pregunta: ¿Tu negocio te da ingresos o te está dejando bienes?", s_cta="Comentar",
 li="No es igual crear un emprendimiento que crear un patrimonio.\n\nUn emprendimiento vende, factura y depende de tu trabajo. Un patrimonio es lo que queda: bienes y derechos que son tuyos, documentados y protegidos. Un negocio puede producir mucho y aun así no dejarte nada propio.\n\nPor eso, desde el primer día de un negocio conviene separar lo que es del negocio de lo que es tuyo: las cuentas, los registros y las decisiones.\n\nSi emprendés, ¿tu negocio te da ingresos o te está dejando bienes? Me interesa leer cómo lo ven otras emprendedoras.",
 li_h="#Emprendimiento #Patrimonio #AutonomiaEconomica"),
# ---------------- SEMANA 3
dict(id="W03", tema="Revisión periódica de bienes en registros públicos", fecha_c="2026-10-27", fecha_li="2026-10-28", fecha_s="2026-10-29", slug="revision-de-registros-publicos",
 flags=["Basado en tu texto 'un secreto, amigas'. La afirmación sobre tus clientes es tuya: confirmá que podés decirla así (sin identificar a nadie)."],
 verificar=["Cómo se hace en la práctica la consulta/estudio de registro en Costa Rica (qué se puede pedir y dónde); confirmar la redacción de la lista."],
 c_slides=[
  ("cover","El hábito de quienes ya consolidaron su patrimonio","Un secreto, amigas"),
  ("statement","En mi experiencia, quienes ya tienen su patrimonio consolidado revisan periódicamente sus bienes en los registros públicos.",""),
  ("list","Qué se revisa",["A nombre de quién figura cada bien","Si hay anotaciones o gravámenes","Si los datos coinciden con lo que creés","Si tus estructuras legales están al día"]),
  ("question","¿Cuándo fue la última vez que revisaste lo que figura a tu nombre?","",None),
  ("question","Si tenés una sociedad: ¿su personería, sus libros y sus representantes están al día?","",None),
  ("statement","No es desconfianza. Es mantenimiento.",""),
  ("close","Anotá una fecha este año para hacerlo. Revisar es parte de tener un patrimonio.",DISC),
 ],
 c_ig="Un secreto, amigas.\n\nEn mi experiencia, quienes ya tienen su patrimonio consolidado revisan de forma periódica sus bienes en los registros públicos y verifican que sus estructuras legales estén actualizadas.\n\nNo es desconfianza: es mantenimiento. ¿Cuándo fue la última vez que revisaste lo que figura a tu nombre?\n\nInformación general sobre Costa Rica; no sustituye asesoría jurídica.",
 c_fb="Un secreto, amigas.\n\nEn mi experiencia, quienes ya tienen su patrimonio consolidado revisan de forma periódica sus bienes en los registros públicos y verifican que sus estructuras legales estén actualizadas: que todo figure a nombre de quien debe, que no haya sorpresas y que las sociedades tengan sus libros y su personería al día.\n\nNo es desconfianza: es mantenimiento. ¿Cuándo fue la última vez que revisaste lo que figura a tu nombre?\n\nInformación general sobre Costa Rica; no sustituye asesoría jurídica.",
 c_h=H["ley"], c_alt="Carrusel de 7 diapositivas. Habla de la revisión periódica de bienes en registros públicos: a nombre de quién figura cada bien, anotaciones o gravámenes, coincidencia de datos y estructuras legales al día. Cierre: Anotá una fecha este año.", c_cta="Guardar y anotar una fecha de revisión",
 s=("quote","Un secreto, amigas: revisar tus bienes en los registros públicos no es desconfianza. Es mantenimiento.",""),
 s_ig="Guardala para acordarte de anotar una fecha.", s_fb="Guardala para acordarte de anotar una fecha. Información general sobre Costa Rica; no sustituye asesoría jurídica.",
 s_h="#Patrimonio #MujeresYDinero #CostaRica", s_alt="Imagen malva con la frase: Un secreto, amigas: revisar tus bienes en los registros públicos no es desconfianza. Es mantenimiento.", s_cta="Guardar",
 li="Un secreto que comparto con colegas y amigas.\n\nEn mi experiencia, las personas que ya tienen su patrimonio consolidado hacen algo que casi nadie más hace: revisan periódicamente sus bienes en los registros públicos y verifican que todas sus estructuras legales estén actualizadas.\n\nNo es desconfianza. Es mantenimiento. Se trata de comprobar que cada bien figure a nombre de quien debe, que los datos coincidan con lo que se cree y que, si hay sociedades, su personería y sus libros estén al día.\n\nPara quien está empezando, el hábito es el mismo: elegí una fecha del año y hacelo. ¿Cada cuánto revisás lo que figura a tu nombre?\n\nInformación general sobre Costa Rica.",
 li_h="#Patrimonio #SeguridadJuridica #Emprendimiento"),
# ---------------- SEMANA 4
dict(id="W04", tema="Nunca es tarde (relato personal)", fecha_c="2026-11-03", fecha_li="2026-11-04", fecha_s="2026-11-05", slug="nunca-es-tarde",
 flags=["RELATO PERSONAL: es tuyo, adaptado de tu mensaje. Requiere tu aprobación explícita antes de publicarse."], verificar=[],
 c_slides=[
  ("cover","Lo que haría distinto, y lo que todavía se puede hacer","Una confesión sobre patrimonio"),
  ("statement","En mis años mozos mi experiencia con esto fue muy floja. No había entendido la importancia del tema.",""),
  ("statement","Pensaba construir una carrera y anhelaba comprar mis activos, pero mis acciones no iban en esa dirección.",""),
  ("statement","Hoy, mirando atrás, reconozco mis sabotajes: lo que decía querer y lo que hacía no coincidían.",""),
  ("statement","Nunca es tarde. Todo finalmente funciona, aunque tal vez más lento o con más dificultad.",""),
  ("question","¿En qué coinciden tus metas y tus acciones? ¿Y en qué no?","",None),
  ("close","Empezar tarde también es empezar.",NL),
 ],
 c_ig="Debo confesar algo.\n\nEn mis años mozos mi experiencia con el patrimonio fue muy floja. No había entendido la importancia del tema. Quería construir una carrera y comprar mis activos, pero mis acciones no iban en esa dirección.\n\nHoy, mirando atrás, reconozco mis sabotajes. Y también sé que nunca es tarde: todo finalmente funciona, aunque tal vez más lento o con más dificultad.\n\n¿En qué coinciden tus metas y tus acciones?",
 c_fb="Debo confesar algo.\n\nEn mis años mozos mi experiencia con el patrimonio fue muy floja. No había entendido la importancia del tema. Anhelaba construir una carrera y empezar a comprar mis activos, pero había una inconsistencia entre lo que quería y lo que hacía.\n\nHoy, mirando atrás, reconozco mis sabotajes. Y también sé que nunca es tarde: todo finalmente funciona, aunque tal vez más lento o con más dificultad.\n\n¿En qué coinciden hoy tus metas y tus acciones? Si querés, contame.",
 c_h=H["pat"], c_alt="Carrusel de 7 diapositivas en primera persona sobre una confesión: la autora reconoce que en su juventud no entendió la importancia del patrimonio, que sus acciones no coincidían con sus metas y que nunca es tarde para empezar.", c_cta="Responder la pregunta en comentarios",
 s=("quote","Nunca es tarde. Todo funciona, aunque sea más lento o con más dificultad.",""),
 s_ig="Si hoy estás empezando, estás a tiempo.", s_fb="Si hoy estás empezando, estás a tiempo. Contame qué decisión querés tomar primero.",
 s_h="#MujeresYDinero #Patrimonio #AutonomiaEconomica", s_alt="Imagen con la frase: Nunca es tarde. Todo funciona, aunque sea más lento o con más dificultad.", s_cta="Comentar",
 li="Debo confesar algo.\n\nEn mis años mozos mi experiencia con el patrimonio fue muy floja. No había entendido la importancia del tema. Pensaba construir una carrera y anhelaba empezar a comprar mis activos, pero había una inconsistencia entre lo que quería y lo que hacía.\n\nHoy, mirando atrás, reconozco mis sabotajes.\n\nTambién descubrí algo que me sirve y quiero compartir: nunca es tarde. Todo finalmente funciona, aunque tal vez más lento o con más dificultad.\n\nSi trabajás con mujeres o sos una de ellas: ¿en qué coinciden hoy tus metas y tus acciones?",
 li_h="#AutonomiaEconomica #Patrimonio #MujeresYDinero"),
# ---------------- SEMANA 5
dict(id="W05", tema="Creencias heredadas del sistema económico", fecha_c="2026-11-10", fecha_li="2026-11-11", fecha_s="2026-11-12", slug="creencias-heredadas",
 flags=["Basado en tu texto sobre creencias y sistema económico. Omití la frase 'con nuestros cuerpos'; decime si querés incluirla.", "Afirmación histórica ('el control de nuestro dinero es reciente'): es tuya; conviene tener un dato o fuente para respaldarla si te la cuestionan."],
 verificar=["Respaldo histórico para 'el control de nuestro dinero es reciente'."],
 c_slides=[
  ("cover","Creencias que heredamos del sistema económico","Y que conviene mirar de frente"),
  ("statement","El control de nuestro dinero es reciente. Antes, para nosotras, no existía.",""),
  ("statement","Aun así, siempre producimos ingresos: con nuestro esfuerzo no retribuido y con una mentalidad de administradoras y salvadoras.",""),
  ("statement","Una mentalidad que muy frecuentemente resulta de provecho a los demás más que a nosotras mismas.",""),
  ("question","¿Para quién trabaja tu manera de cuidar?","",None),
  ("question","¿Qué creencia sobre el dinero heredaste sin haberla elegido?","",None),
  ("close","Mirar una creencia es el primer paso para decidir si la conservás.",NL),
 ],
 c_ig="Hay creencias en nuestra mente que vienen de cómo se configuró el sistema económico.\n\nEl control de nuestro dinero es reciente. Y aun así siempre produjimos ingresos: con esfuerzo no retribuido y con una mentalidad de administradoras y salvadoras que muchas veces beneficia más a otras personas que a nosotras.\n\n¿Qué creencia sobre el dinero heredaste sin haberla elegido?",
 c_fb="Hay creencias en nuestra mente que vienen de cómo se configuró el sistema económico.\n\nEl control de nuestro dinero es reciente. Y aun así siempre produjimos ingresos: con nuestro esfuerzo no retribuido y con una mentalidad de administradoras y salvadoras que muy frecuentemente resulta de provecho a los demás más que a nosotras mismas.\n\nNo se trata de dejar de cuidar, sino de mirar para quién trabaja ese cuidado. ¿Qué creencia sobre el dinero heredaste sin haberla elegido?",
 c_h=H["pat"], c_alt="Carrusel de 7 diapositivas sobre creencias heredadas: el control del dinero de las mujeres es reciente, el esfuerzo no retribuido y la mentalidad de administradoras y salvadoras que beneficia a otros. Preguntas: para quién trabaja tu manera de cuidar y qué creencia heredaste.", c_cta="Responder la pregunta en comentarios",
 s=("question","¿Para quién trabaja tu manera de cuidar?","Administradoras y salvadoras: ¿a quién beneficia más?"),
 s_ig="No hay respuesta correcta. Hay una respuesta honesta.", s_fb="No hay respuesta correcta, hay una respuesta honesta. Si querés compartirla, estoy leyendo.",
 s_h="#MujeresYDinero #AutonomiaEconomica #Cuidados", s_alt="Imagen clara con la pregunta: ¿Para quién trabaja tu manera de cuidar? Subtítulo: Administradoras y salvadoras, ¿a quién beneficia más?", s_cta="Comentar",
 li="Hay creencias sobre el dinero que no elegimos: las heredamos de cómo se configuró el sistema económico.\n\nEl control de nuestro propio dinero es reciente. Y aun así las mujeres siempre produjimos ingresos: con nuestro esfuerzo no retribuido y con una mentalidad de administradoras y salvadoras que, muy frecuentemente, resulta de provecho a los demás más que a nosotras mismas.\n\nNo se trata de dejar de cuidar. Se trata de ver para quién trabaja ese cuidado.\n\n¿Qué creencia sobre el dinero heredaste sin haberla elegido?",
 li_h="#AutonomiaEconomica #MujeresYDinero #Liderazgo"),
# ---------------- SEMANA 6
dict(id="W06", tema="Separar cuentas del negocio y personales", fecha_c="2026-11-17", fecha_li="2026-11-18", fecha_s="2026-11-19", slug="separar-cuentas",
 flags=["Basado en tu libro (pp. 51 y 64). Los pasos de la diapositiva 4 son propuesta mía."], verificar=[],
 c_slides=[
  ("cover","Tu cuenta personal y la de tu negocio no deberían ser la misma","Un primer paso para ordenar lo que construís"),
  ("statement","Cuando se mezclan, es difícil saber con certeza si el negocio gana o pierde.",""),
  ("list","Lo que se complica si se mezclan",["Saber si el negocio da ganancias","Justificar tus declaraciones de impuestos","Pedir financiamiento","Distinguir lo tuyo de lo del negocio"]),
  ("list","Un primer paso",["Abrí una cuenta solo para el negocio","Definí cuánto te pagás cada mes","Guardá los comprobantes","Revisá el movimiento una vez al mes"]),
  ("question","¿Cuál de estos pasos podés dar esta semana?","",None),
  ("close","Ordenar no es burocracia. Es poder decidir con información.",NL),
 ],
 c_ig="Cuando la cuenta del negocio y la de la casa son la misma, es difícil saber con certeza si el negocio gana o pierde.\n\nY además se complica justificar impuestos, pedir financiamiento y distinguir lo tuyo de lo del negocio.\n\nUn primer paso: una cuenta solo para el negocio y un monto fijo que te pagás cada mes. ¿Cuál de los pasos podés dar esta semana?",
 c_fb="Cuando la cuenta del negocio y la de la casa son la misma, es difícil saber con certeza si el negocio gana o pierde.\n\nY además se complica justificar impuestos, pedir financiamiento y distinguir lo tuyo de lo del negocio.\n\nUn primer paso posible: una cuenta solo para el negocio, un monto fijo que te pagás cada mes y los comprobantes guardados. ¿Cuál de esos pasos podés dar esta semana?",
 c_h=H["emp"], c_alt="Carrusel de 6 diapositivas sobre separar la cuenta personal de la del negocio. Explica qué se complica al mezclar y propone cuatro primeros pasos: cuenta aparte, monto fijo, comprobantes y revisión mensual.", c_cta="Responder qué paso darán esta semana",
 s=("quote","Si no podés separar lo que es tuyo de lo que es del negocio, tampoco podés medir lo que construiste.",""),
 s_ig="Un solo paso esta semana ya cambia el panorama.", s_fb="Un solo paso esta semana ya cambia el panorama. ¿Cuál vas a dar?",
 s_h="#EmprendedorasCR #FinanzasPersonales #Emprendimiento", s_alt="Imagen malva con la frase: Si no podés separar lo que es tuyo de lo que es del negocio, tampoco podés medir lo que construiste.", s_cta="Comentar",
 li="Uno de los errores más comunes que veo en emprendimientos es usar la misma cuenta bancaria para el negocio y para los gastos personales.\n\nEl resultado: es difícil saber con certeza si el negocio gana o pierde, se complica justificar la información de impuestos y se vuelve más difícil financiarlo, porque los reportes no reflejan la realidad del negocio.\n\nUn primer paso sencillo: una cuenta solo para el negocio, un monto fijo que te pagás cada mes, comprobantes guardados y una revisión mensual.\n\nOrdenar no es burocracia. Es poder decidir con información. ¿Qué paso darías esta semana?",
 li_h="#Emprendimiento #FinanzasPersonales #Pymes"),
# ---------------- SEMANA 7
dict(id="W07", tema="Tres obstáculos entre arrancar y consolidar", fecha_c="2026-11-24", fecha_li="2026-11-25", fecha_s="2026-11-26", slug="tres-obstaculos",
 flags=["Basado en tu artículo del 28 de agosto. Sin cifras en las piezas hasta verificar los informes."],
 verificar=["Confirmar las cifras de GEM 2024/2025 e IV Informe de Brechas INAMU antes de citar números. La pieza solo usa la tesis."],
 c_slides=[
  ("cover","Arrancar no es el obstáculo. Consolidar sí.","Tres frenos entre el primer año y el negocio que se sostiene"),
  ("statement","Muchas mujeres arrancan un negocio. Menos llegan a consolidarlo.",""),
  ("question","Formalización","Seguir como persona física sin separar el patrimonio personal del del negocio.","1"),
  ("question","Patrimonio como garantía","Pedir crédito suele implicar dar algo propio como respaldo, y no todas tenemos bienes a nuestro nombre.","2"),
  ("question","Reportes ordenados","Sin reportes financieros al día, acceder a crédito es más difícil.","3"),
  ("question","¿Cuál de los tres es tu freno hoy?","",None),
  ("close","Fuentes: GEM Costa Rica 2024/2025 e IV Informe de Brechas (INAMU). Lectura propia.",NL),
 ],
 c_ig="Arrancar no es el obstáculo principal. Sostener y consolidar sí lo es.\n\nAl leer juntos el informe GEM de Costa Rica y el informe de brechas financieras del INAMU, aparecen tres frenos: la formalización, el patrimonio como garantía y los reportes ordenados.\n\n¿Cuál de los tres es el tuyo?\n\nFuentes en la última diapositiva.",
 c_fb="Arrancar no es el obstáculo principal para las mujeres que emprenden en Costa Rica. Sostener y consolidar sí lo es.\n\nAl leer juntos el informe GEM y el informe de brechas financieras del INAMU aparecen tres frenos: la formalización, el patrimonio como garantía para el crédito y los reportes financieros ordenados.\n\n¿Cuál de los tres es el tuyo? Las fuentes están en la última diapositiva.",
 c_h=H["emp"], c_alt="Carrusel de 7 diapositivas. Tesis: arrancar no es el obstáculo, consolidar sí. Tres frenos numerados: formalización, patrimonio como garantía y reportes ordenados. Última diapositiva con las fuentes: GEM Costa Rica 2024/2025 e informe del INAMU.", c_cta="Comentar cuál es tu freno; leer el artículo del Substack",
 s=("quote","Arrancar no es el obstáculo principal. Sostener y consolidar sí lo es.",""),
 s_ig="Fuentes: GEM Costa Rica 2024/2025 e IV Informe de Brechas (INAMU). Lectura propia.", s_fb="Fuentes: GEM Costa Rica 2024/2025 e IV Informe de Brechas (INAMU). Lectura propia. ¿Qué opinás?",
 s_h="#EmprendedorasCR #MujeresYDinero #Emprendimiento", s_alt="Imagen malva con la frase: Arrancar no es el obstáculo principal. Sostener y consolidar sí lo es.", s_cta="Comentar",
 li="Arrancar no es, para las mujeres que emprenden en Costa Rica, el obstáculo principal. Sostener y consolidar sí lo es.\n\nAl leer juntos el informe GEM de Costa Rica y el informe de brechas financieras del INAMU, aparecen tres frenos que se repiten justo en ese tramo:\n\n1. La formalización: negocios que siguen como persona física y no separan patrimonios.\n2. El patrimonio como garantía: pedir crédito suele implicar dar algo propio, y no todas tenemos bienes a nuestro nombre.\n3. Los reportes: sin información financiera ordenada es más difícil acceder a crédito productivo.\n\nFuentes: GEM Costa Rica 2024/2025 e IV Informe de Brechas (INAMU). ¿Cuál de los tres identificás más en los negocios que conocés?",
 li_h="#Emprendimiento #InclusionFinanciera #Pymes"),
# ---------------- SEMANA 8
dict(id="W08", tema="Libros legales de la sociedad", fecha_c="2026-12-01", fecha_li="2026-12-02", fecha_s="2026-12-03", slug="libros-legales",
 flags=["Basado en tu libro (pp. 29-33). Contiene un llamado a consultar: activar SOLO si ya existe el formulario; si no, reemplazar por 'guardá esta publicación'."],
 verificar=["Lista de libros legales de la S.A. y de la S.R.L. según el Código de Comercio vigente."],
 c_slides=[
  ("cover","¿Dónde están los libros de tu sociedad?","Una pregunta que conviene hacerse antes de que alguien la haga"),
  ("statement","Una sociedad tiene libros legales. Quien administra debe poder demostrar que los lleva al día.",""),
  ("list","Entre los libros de una sociedad anónima",["Asambleas de socios","Junta directiva","Registro de accionistas","Diario, Mayor e Inventarios y balances"]),
  ("question","¿Quién los guarda? ¿Los has visto alguna vez?","",None),
  ("question","¿Las actas de tus últimas decisiones están firmadas y asentadas?","",None),
  ("close","Si querés revisar el caso de tu sociedad, el formulario está en el enlace del perfil.",DISC),
 ],
 c_ig="Tu sociedad tiene libros legales. ¿Sabés dónde están?\n\nQuien administra una sociedad debe poder demostrar que los lleva al día: actas, registro de accionistas, libros contables.\n\nPregunta para hoy: ¿quién los guarda y cuándo fue la última vez que los viste?\n\nInformación general sobre Costa Rica; no sustituye asesoría jurídica.",
 c_fb="Tu sociedad tiene libros legales. ¿Sabés dónde están?\n\nQuien administra una sociedad debe poder demostrar que los lleva al día: las actas de asamblea y de junta directiva, el registro de accionistas, los libros contables. Esa documentación también es prueba de una gestión diligente.\n\nPregunta para hoy: ¿quién los guarda y cuándo fue la última vez que los viste?\n\nInformación general sobre Costa Rica; no sustituye asesoría jurídica.",
 c_h=H["ley"], c_alt="Carrusel de 6 diapositivas sobre los libros legales de una sociedad: asambleas de socios, junta directiva, registro de accionistas y libros contables. Preguntas sobre quién los guarda y si las actas están firmadas y asentadas.", c_cta="Responder o consultar por el formulario",
 s=("question","¿Tu sociedad \"dormida\" está al día?",""),
 s_ig="Una sociedad sin actividad también merece una revisión.", s_fb="Una sociedad sin actividad también merece una revisión. Información general sobre Costa Rica; no sustituye asesoría jurídica.",
 s_h="#SociedadesMercantiles #CostaRica #Patrimonio", s_alt="Imagen clara con la pregunta: ¿Tu sociedad dormida está al día?", s_cta="Guardar / consultar",
 li="¿Dónde están los libros de tu sociedad?\n\nUna sociedad tiene libros legales: asambleas de socios, junta directiva, registro de accionistas y libros contables. Quien administra debe poder demostrar que los lleva al día; esa documentación es prueba de una gestión diligente.\n\nTres preguntas útiles:\n1. ¿Quién los guarda?\n2. ¿Las actas de las últimas decisiones están firmadas y asentadas?\n3. ¿Si hay una sociedad sin actividad, está al día en lo que le corresponde?\n\nInformación general sobre Costa Rica; no sustituye asesoría jurídica. ¿Habías visto los libros de tu sociedad?",
 li_h="#SociedadesMercantiles #Emprendimiento #CostaRica"),
# ---------------- SEMANA 9
dict(id="W09", tema="Aceptar un cargo en una sociedad", fecha_c="2026-12-08", fecha_li="2026-12-09", fecha_s="2026-12-10", slug="cargo-en-sociedad", reuse="2026-10-13_IG-FB_carrusel_presidenta-de-sociedad",
 flags=["Carrusel ya producido (8 diapositivas, portada incluida). Pendiente verificar la norma de responsabilidad del representante legal."],
 verificar=["Responsabilidad personal del representante legal por deudas con Hacienda y CCSS (tu libro pp. 26-28, nota 23)."],
 c_slides=None,
 c_ig="Hay cargos que se aceptan con una sonrisa y una firma: presidenta, tesorera, representante legal. Y hay obligaciones que vienen con el cargo aunque nadie las haya mencionado.\n\nAntes de decir que sí, estas cinco preguntas ordenan la conversación. No son una acusación para quien te lo propone: son una forma de entender qué estarías firmando.\n\n¿Te pidieron alguna vez ocupar un puesto así? Contame qué preguntarías vos.\n\nInformación general sobre Costa Rica; no sustituye asesoría jurídica.",
 c_fb="Hay cargos que se aceptan con una sonrisa y una firma: presidenta, tesorera, representante legal. Y hay obligaciones que vienen con el cargo aunque nadie las haya mencionado.\n\nAntes de decir que sí, estas cinco preguntas ordenan la conversación. No son una acusación para quien te lo propone: son una forma de entender qué estarías firmando.\n\n¿Te pidieron alguna vez ocupar un puesto así? Contame qué preguntarías vos.\n\nInformación general sobre Costa Rica; no sustituye asesoría jurídica.",
 c_h=H["ley"], c_alt="Carrusel de 8 diapositivas en tonos malva y claros sobre cinco preguntas antes de aceptar ser presidenta de una sociedad. La última muestra la portada del libro.", c_cta="Comentar qué preguntarías",
 s=("question","¿Por qué me lo piden a mí y no a otra persona?","Una pregunta legítima antes de aceptar un cargo."),
 s_ig="La respuesta dice mucho sobre lo que se espera de tu firma.", s_fb="La respuesta dice mucho sobre lo que se espera de tu firma. Información general sobre Costa Rica.",
 s_h="#SociedadesMercantiles #CostaRica #EmprendedorasCR", s_alt="Imagen clara con la pregunta: ¿Por qué me lo piden a mí y no a otra persona? Subtítulo: Una pregunta legítima antes de aceptar un cargo.", s_cta="Comentar",
 li="Es como ser fiadora sin que nunca nos hayan preguntado si queríamos serlo.\n\nAsí describo la situación de quien acepta un cargo en una sociedad (presidenta, tesorera, representante legal) sin revisar qué obligaciones trae.\n\nCinco preguntas antes de decir que sí:\n1. ¿Para qué existe esta sociedad y qué papel tendría yo?\n2. ¿Quién gestiona el negocio y quién maneja el dinero?\n3. ¿Están los libros legales y las actas al día? ¿Dónde están?\n4. ¿Se pagan los impuestos y las cargas sociales?\n5. ¿Por qué me lo piden a mí y no a otra persona?\n\nInformación general sobre Costa Rica; no sustituye asesoría jurídica. ¿Qué preguntarías vos?",
 li_h="#SociedadesMercantiles #Emprendimiento #CostaRica"),
# ---------------- SEMANA 10
dict(id="W10", tema="El libro que me hubiera gustado tener", fecha_c="2026-12-15", fecha_li="2026-12-16", fecha_s="2026-12-17", slug="el-libro",
 flags=["Basado en tu artículo 'El libro' (Substack). Incluye la portada real. Confirmá el enlace de Amazon y el precio antes de programar."], verificar=[],
 c_slides=[
  ("cover","El libro que me hubiera gustado tener a mano","Mujeres generándose riqueza: Manual para emprendedoras"),
  ("statement","Lo escribí para cada mujer que llegaba a mi consulta sintiendo que \"los temas de plata no eran para ella\".",""),
  ("list","Lo que recorre, paso a paso",["Cómo proteger el patrimonio desde el día uno","Emprender a tu nombre o formar una sociedad","Un presupuesto que de verdad se sostenga","Leer tus números sin ser contadora"]),
  ("list","Y también",["Perderle el miedo a los impuestos","Hacia dónde va la tecnología financiera"]),
  ("book","Esa explicación es lo que faltaba. Empecemos por ahí.","eBook en Amazon: enlace en el perfil"),
 ],
 c_ig="Lo escribí como el libro que me hubiera gustado tener a mano en cada consulta, para dárselo a cada mujer que llegaba sintiendo que los temas de plata no eran para ella.\n\nRecorre, paso a paso: cómo proteger el patrimonio desde el día uno, cómo elegir entre emprender a tu nombre o formar una sociedad, cómo armar un presupuesto que se sostenga y cómo leer tus números sin ser contadora.\n\nMujeres generándose riqueza: Manual para emprendedoras. eBook en Amazon, enlace en el perfil.",
 c_fb="Lo escribí como el libro que me hubiera gustado tener a mano en cada consulta, para dárselo a cada mujer que llegaba sintiendo que los temas de plata no eran para ella.\n\nRecorre, paso a paso: cómo proteger el patrimonio desde el día uno, cómo elegir entre emprender a tu nombre o formar una sociedad, cómo armar un presupuesto que se sostenga, cómo leer tus números sin ser contadora y cómo perderle el miedo a los impuestos.\n\nMujeres generándose riqueza: Manual para emprendedoras. eBook en Amazon. [ENLACE]",
 c_h=H["esc"], c_alt="Carrusel de 5 diapositivas sobre el eBook Mujeres generándose riqueza: Manual para emprendedoras. Presenta lo que recorre el libro y muestra la portada en la última diapositiva.", c_cta="Comprar el eBook (enlace)",
 s=("quote","Esa explicación es lo que faltaba. Empecemos por ahí.","Mujeres generándose riqueza · eBook en Amazon"),
 s_ig="Enlace en el perfil.", s_fb="eBook en Amazon: [ENLACE].",
 s_h="#MujeresGenerandoseRiqueza #MujeresYDinero #Escritoras", s_alt="Imagen malva con la frase: Esa explicación es lo que faltaba. Empecemos por ahí. Subtítulo: Mujeres generándose riqueza, eBook en Amazon.", s_cta="Enlace",
 li="Escribí Mujeres generándose riqueza: Manual para emprendedoras como el libro que me hubiera gustado tener a mano en cada consulta.\n\nLo pensé para cada mujer que llegaba sintiendo que \"los temas de plata no eran para ella\". Recorre, paso a paso, cómo proteger el patrimonio desde el día uno, cómo elegir entre emprender a tu nombre o formar una sociedad, cómo armar un presupuesto que se sostenga y cómo leer tus números sin ser contadora.\n\nEstoy reinventándome como escritora, y este es mi primer paso. Si lo leés, me interesa saber qué te sirvió y qué faltó.\n\nEnlace al eBook en Amazon: [ENLACE]",
 li_h="#Emprendimiento #MujeresYDinero #Autoras"),
# ---------------- SEMANA 11
dict(id="W11", tema="Cinco preguntas para cerrar el año", fecha_c="2026-12-22", fecha_li="2026-12-23", fecha_s=None, slug="cierre-de-ano",
 flags=["Solo preguntas; sin datos ni normas."], verificar=[],
 c_slides=[
  ("cover","Cinco preguntas para cerrar el año con tu dinero y tu negocio","Sin balances ni culpas"),
  ("question","¿Cuánto de lo que ganaste este año se convirtió en algo duradero?","","1"),
  ("question","¿Qué de lo que construiste figura realmente a tu nombre?","","2"),
  ("question","¿Qué acuerdo económico importante sigue solo de palabra?","","3"),
  ("question","¿Qué decisión de dinero postergaste y por qué?","","4"),
  ("question","¿Qué querés que sea distinto en tu patrimonio dentro de un año?","","5"),
  ("close","Elegí una pregunta y contestala por escrito. Con una alcanza para empezar.",NL),
 ],
 c_ig="Antes de que termine el año, cinco preguntas. Sin balances y sin culpas.\n\nElegí una y contestala por escrito. Con una alcanza para empezar. Y si querés compartirla, estoy leyendo.",
 c_fb="Antes de que termine el año, cinco preguntas sobre tu dinero y tu negocio. Sin balances y sin culpas.\n\nElegí una y contestala por escrito. Con una alcanza para empezar. Y si querés compartirla acá, estoy leyendo.",
 c_h=H["pat"], c_alt="Carrusel de 7 diapositivas con cinco preguntas numeradas para cerrar el año sobre ingresos duraderos, bienes a tu nombre, acuerdos de palabra, decisiones postergadas y metas de patrimonio.", c_cta="Elegir una pregunta y comentar",
 s=None, s_ig=None, s_fb=None, s_h=None, s_alt=None, s_cta=None,
 li="Antes de que termine el año, cinco preguntas sobre dinero y patrimonio. Sin balances y sin culpas:\n\n1. ¿Cuánto de lo que ganaste este año se convirtió en algo duradero?\n2. ¿Qué de lo que construiste figura realmente a tu nombre?\n3. ¿Qué acuerdo económico importante sigue solo de palabra?\n4. ¿Qué decisión de dinero postergaste y por qué?\n5. ¿Qué querés que sea distinto en tu patrimonio dentro de un año?\n\nElegí una y contestala por escrito. Con una alcanza para empezar.",
 li_h="#Patrimonio #CierreDeAño #AutonomiaEconomica"),
# ---------------- SEMANA 12
dict(id="W12", tema="Lo que quiero seguir preguntando en 2027", fecha_c="2026-12-29", fecha_li="2026-12-30", fecha_s="2026-12-31", slug="preguntas-2027",
 flags=["Las preguntas salen de tus textos. Si preferís otras para 2027, cambialas."], verificar=[],
 c_slides=[
  ("cover","Lo que quiero seguir preguntando en 2027","Cinco preguntas sobre dinero, poder y autonomía"),
  ("question","¿Por qué a las mujeres no nos enseñaron de dinero?","","1"),
  ("question","¿Qué parte de nuestros límites es legal y qué parte es costumbre?","","2"),
  ("question","¿Cómo se valora el trabajo doméstico y de cuidado?","","3"),
  ("question","¿Qué estructuras protegen realmente un patrimonio?","","4"),
  ("question","¿Qué mujeres están construyendo patrimonio y cómo lo hicieron?","","5"),
  ("close","Contame qué pregunta querés que explore el próximo año.",NL),
 ],
 c_ig="Cierro el año con las preguntas que quiero seguir explorando en 2027.\n\nSobre dinero, poder y autonomía de las mujeres. ¿Cuál te interesa más? ¿Falta alguna? Contame y la sumo.",
 c_fb="Cierro el año con las preguntas que quiero seguir explorando en 2027, sobre dinero, poder y autonomía de las mujeres.\n\n¿Cuál te interesa más? ¿Falta alguna? Contame en los comentarios y la sumo a la lista.",
 c_h=H["esc"], c_alt="Carrusel de 7 diapositivas con cinco preguntas para 2027 sobre por qué a las mujeres no nos enseñaron de dinero, límites legales y costumbres, valoración del trabajo de cuidado, estructuras de protección del patrimonio y mujeres que construyen patrimonio.", c_cta="Proponer una pregunta en comentarios",
 s=("quote","En 2027, que lo que ganes se convierta en algo tuyo.",""),
 s_ig="Feliz cierre de año. Gracias por leerme.", s_fb="Feliz cierre de año. Gracias por leerme y por conversar.",
 s_h="#MujeresYDinero #Patrimonio #AutonomiaEconomica", s_alt="Imagen malva con la frase: En 2027, que lo que ganes se convierta en algo tuyo.", s_cta="Comentar",
 li="Cierro el año con las preguntas que quiero seguir explorando en 2027:\n\n- ¿Por qué a las mujeres no nos enseñaron de dinero?\n- ¿Qué parte de nuestros límites es legal y qué parte es costumbre?\n- ¿Cómo se valora el trabajo doméstico y de cuidado?\n- ¿Qué estructuras protegen realmente un patrimonio?\n- ¿Qué mujeres están construyendo patrimonio y cómo lo hicieron?\n\nGracias por leerme este año. ¿Qué pregunta te gustaría que explore?",
 li_h="#AutonomiaEconomica #MujeresYDinero #Patrimonio"),
]
